# Menu config
# 菜单配置

[[main]]
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = "<i class='fas fa-archive fa-fw'></i>"
# you can add extra information after the name (HTML format is supported), such as icons
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "归档"
url = "/posts/"
# title will be shown when you hover on this menu link.
# 将鼠标悬停在此菜单链接上时将显示标题。
title = ""
weight = 1
[[main]]
identifier = "tags"
pre = "<i class='fas fa-tags fa-fw'></i>"
post = ""
name = "标签"
url = "/tags/"
title = ""
weight = 2
[[main]]
identifier = "categories"
pre = "<i class='fas fa-th-large fa-fw'></i>"
post = ""
name = "分类"
url = "/categories/"
title = ""
weight = 3
[[main]]
identifier = "series"
pre = "<i class='fas fa-book fa-fw'></i>"
post = ""
name = "系列"
url = "/series/"
title = ""
weight = 4
[[main]]
identifier = "about"
pre = "<i class='fas fa-user fa-fw'></i>"
post = ""
name = "关于"
url = "/about/"
title = ""
weight = 5
